- name: Deploy 
  uses: JamesIves/github-pages-deploy-action@4.1.0
  with:
    branch: main # The branch the action should deploy to.
    folder: dist # The folder the action should deploy.
    token: ${{ secrets.TOKEN }}
    repository-name: ${{ env.owner }}/${{ env.repo }}
